# This is a basic workflow to help you get started with Actions

name: extract-tapermonkey-scripts-v2

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      path:
        description: 'input zip/tar file full path'
        required: true
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - run: pwd
      - run: tree -a
      - run: echo "The input path is:[${{ inputs.path }}]"
      - run: pip install leveldb
      - run: rm -rf result
      - run: mkdir result
      - run: python py2.py "${{ inputs.path }}"
      - run: tree -a -I .git
      # move files to result dir and ignore error
      - run: mv extract_tampermonkey_script_output result 2>/dev/null ||true
      - run: mv github-action-run.log result 2>/dev/null ||true
      - uses: actions/upload-artifact@v3
        with:
          name: artifact-tampermonkey-extract-output
          path: result
      - run: echo finished

